name: Build Run Check Coding Conventions

on:
  push:
    branches: 
  pull_request:
    branches: 

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Swift Format
      run: brew install swiftformat
    
    - name: Format the code
      run: swiftformat Hackenschmidt/

    - name: Commit and push changes
      run: |
        git remote set-url origin ${{ secrets.SSH_SECRET }}
        git status
        git add .
        git commit -m "Auto formatting swift files with swiftformat"
        git push
