name: Check Coding Conventions

on:
  push:
    branches: 
  pull_request:
    branches: 

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Swift Format
      run: swiftformat . --config .checkstyle