name: Build Run Check Coding Conventions

on:
  push:
    branches: 
  pull_request:
    branches: 

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Check Swift Format
      run: swiftformat . --config .checkstyle